# Generated by Django 5.2.2 on 2025-09-15 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='content.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_boards', to='user_management.user')),
            ],
            options={
                'db_table': 'board_follows',
                'indexes': [models.Index(fields=['user'], name='board_follo_user_id_154872_idx'), models.Index(fields=['board'], name='board_follo_board_i_68c54c_idx')],
                'unique_together': {('user', 'board')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.comment')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_management.user')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user'], name='comments_user_id_8613ff_idx'), models.Index(fields=['pin'], name='comments_pin_id_f41b74_idx'), models.Index(fields=['parent'], name='comments_parent__9f8798_idx'), models.Index(fields=['created_at'], name='comments_created_d5740c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PinLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_pins', to='user_management.user')),
            ],
            options={
                'db_table': 'pin_likes',
                'indexes': [models.Index(fields=['user'], name='pin_likes_user_id_a93b84_idx'), models.Index(fields=['pin'], name='pin_likes_pin_id_7c3478_idx'), models.Index(fields=['created_at'], name='pin_likes_created_c87777_idx')],
                'unique_together': {('user', 'pin')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user_management.user')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_management.user')),
            ],
            options={
                'db_table': 'user_follows',
                'indexes': [models.Index(fields=['follower'], name='user_follow_followe_a0b992_idx'), models.Index(fields=['following'], name='user_follow_followi_eaf074_idx'), models.Index(fields=['created_at'], name='user_follow_created_744e51_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
