# Generated by Django 5.2.2 on 2025-09-15 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('is_private', models.BooleanField(default=False)),
                ('color_theme', models.CharField(default='#000000', max_length=7)),
                ('pin_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='user_management.user')),
            ],
            options={
                'db_table': 'boards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('original_url', models.URLField(blank=True, max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('dominant_color', models.CharField(blank=True, max_length=7)),
                ('is_video', models.BooleanField(default=False)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='content.board')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='content.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='user_management.user')),
            ],
            options={
                'db_table': 'pins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinSave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pins', to='content.board')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='content.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pins', to='user_management.user')),
            ],
            options={
                'db_table': 'pin_saves',
            },
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['user'], name='boards_user_id_58524f_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['created_at'], name='boards_created_4143b0_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_private'], name='boards_is_priv_432ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['user'], name='pins_user_id_fad5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['board'], name='pins_board_i_4f8d05_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['category'], name='pins_categor_586f29_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['created_at'], name='pins_created_1d87df_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['-like_count'], name='pins_like_co_c506c7_idx'),
        ),
        migrations.AddIndex(
            model_name='pinsave',
            index=models.Index(fields=['user'], name='pin_saves_user_id_af1d17_idx'),
        ),
        migrations.AddIndex(
            model_name='pinsave',
            index=models.Index(fields=['pin'], name='pin_saves_pin_id_338228_idx'),
        ),
        migrations.AddIndex(
            model_name='pinsave',
            index=models.Index(fields=['board'], name='pin_saves_board_i_b28e91_idx'),
        ),
        migrations.AddIndex(
            model_name='pinsave',
            index=models.Index(fields=['created_at'], name='pin_saves_created_a6270b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pinsave',
            unique_together={('user', 'pin', 'board')},
        ),
    ]
