# Generated by Django 5.2.2 on 2025-09-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='content.board'),
        ),
        migrations.AddField(
            model_name='pin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='content.category'),
        ),
        migrations.AddField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pinsave',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pins', to='content.board'),
        ),
        migrations.AddField(
            model_name='pinsave',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='content.pin'),
        ),
        migrations.AddField(
            model_name='pinsave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['user'], name='boards_user_id_58524f_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['created_at'], name='boards_created_4143b0_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_private'], name='boards_is_priv_432ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['user'], name='pins_user_id_fad5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['board'], name='pins_board_i_4f8d05_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['category'], name='pins_categor_586f29_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['created_at'], name='pins_created_1d87df_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['-like_count'], name='pins_like_co_c506c7_idx'),
        ),
        migrations.AddIndex(
            model_name='pinsave',
            index=models.Index(fields=['user'], name='pin_saves_user_id_af1d17_idx'),
        ),
        migrations.AddIndex(
            model_name='pinsave',
            index=models.Index(fields=['pin'], name='pin_saves_pin_id_338228_idx'),
        ),
        migrations.AddIndex(
            model_name='pinsave',
            index=models.Index(fields=['board'], name='pin_saves_board_i_b28e91_idx'),
        ),
        migrations.AddIndex(
            model_name='pinsave',
            index=models.Index(fields=['created_at'], name='pin_saves_created_a6270b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pinsave',
            unique_together={('user', 'pin', 'board')},
        ),
    ]
